#!/usr/bin/env bash
set -ex

RELEASE_VERSION="${1}"
RELEASE_TAG="${2}"

cd custom_components/onyx_conversation_agent
zip -r ../../onyx_conversation_agent.zip .
cd ../..

gh release upload "${RELEASE_TAG}" onyx_conversation_agent.zip
